
export const STORAGE_OPTIONS = ['64Gb', '128Gb', '256Gb', '512Gb', '1Tb'];

export const DEFAULT_IPHONE_MODELS = [
  'iPhone X', 'iPhone XR', 'iPhone XS', 'iPhone XS Max',
  'iPhone 11', 'iPhone 11 Pro', 'iPhone 11 Pro Max',
  'iPhone 12', 'iPhone 12 Mini', 'iPhone 12 Pro', 'iPhone 12 Pro Max',
  'iPhone 13', 'iPhone 13 Mini', 'iPhone 13 Pro', 'iPhone 13 Pro Max',
  'iPhone 14', 'iPhone 14 Plus', 'iPhone 14 Pro', 'iPhone 14 Pro Max',
  'iPhone 15', 'iPhone 15 Plus', 'iPhone 15 Pro', 'iPhone 15 Pro Max',
  'iPhone 16', 'iPhone 16 Plus', 'iPhone 16 Pro', 'iPhone 16 Pro Max'
];

export const DEFAULT_SAMSUNG_MODELS = [
  'Galaxy S10', 'Galaxy S10+', 'Galaxy S10 5G', 'Galaxy S10e',
  'Galaxy S20', 'Galaxy S20+', 'Galaxy S20 Ultra', 'Galaxy S20 FE',
  'Galaxy S21', 'Galaxy S21+', 'Galaxy S21 Ultra', 'Galaxy S21 FE',
  'Galaxy S22', 'Galaxy S22+', 'Galaxy S22 Ultra',
  'Galaxy S23', 'Galaxy S23+', 'Galaxy S23 Ultra', 'Galaxy S23 FE',
  'Galaxy S24', 'Galaxy S24+', 'Galaxy S24 Ultra',
  'Galaxy S25', 'Galaxy S25+', 'Galaxy S25 Ultra',
  'Galaxy S26', 'Galaxy S26+', 'Galaxy S26 Ultra'
];

export const translations = {
  en: {
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    sales: 'Sales Log',
    debtors: 'Debtors',
    analytics: 'Analytics',
    settings: 'Settings',
    addDevice: 'Add Device',
    model: 'Model',
    imei: 'IMEI',
    storage: 'Storage',
    price: 'Price',
    status: 'Status',
    actions: 'Actions',
    sell: 'Sell Now',
    cancel: 'Cancel',
    return: 'Return Item',
    profit: 'Profit',
    totalSales: 'Total Sales',
    inStock: 'In Stock',
    customer: 'Customer',
    date: 'Date',
    installment: 'Installment',
    months: 'Months',
    remaining: 'Remaining',
    search: 'Search by IMEI or Model...',
    save: 'Save Record',
    back: 'Back',
    brand: 'Brand',
    purchasePrice: 'Purchase Price',
    sellingPrice: 'Sale Price',
    purchasedFrom: 'Purchased From',
    purchaseDate: 'Purchase Date',
    yearlyProfit: 'Yearly Profit Overview',
    monthlyPerformance: 'Monthly Performance',
    downPayment: 'Down Payment',
    totalAssets: 'Total Assets',
    stockValue: 'Stock Value',
    cash: 'Cash',
    updateCash: 'Update Cash Balance',
    exchangeRate: 'USD Rate',
    aiInsights: 'AI Business Advisor',
    generateAI: 'Analyze with AI',
    addModel: 'Add New Model',
    manageModels: 'Manage Inventory List',
    pay: 'Pay',
    returned: 'Returned',
    completed: 'Completed'
  },
  ru: {
    dashboard: 'Главная',
    inventory: 'Склад',
    sales: 'Продажи',
    debtors: 'Должники',
    analytics: 'Аналитика',
    settings: 'Настройки',
    addDevice: 'Добавить товар',
    model: 'Модель',
    imei: 'IMEI',
    storage: 'Память',
    price: 'Цена',
    status: 'Статус',
    actions: 'Действия',
    sell: 'Продать сейчас',
    cancel: 'Отмена',
    return: 'Возврат товара',
    profit: 'Прибыль',
    totalSales: 'Всего продаж',
    inStock: 'В наличии',
    customer: 'Клиент',
    date: 'Дата',
    installment: 'Рассрочка',
    months: 'Месяцы',
    remaining: 'Остаток',
    search: 'Поиск по IMEI или модели...',
    save: 'Сохранить',
    back: 'Назад',
    brand: 'Бренд',
    purchasePrice: 'Цена закупа',
    sellingPrice: 'Цена сделки',
    purchasedFrom: 'У кого куплено',
    purchaseDate: 'Дата покупки',
    yearlyProfit: 'Годовая прибыль',
    monthlyPerformance: 'Ежемесячные показатели',
    downPayment: 'Первоначальный взнос',
    totalAssets: 'Итог (Активы)',
    stockValue: 'Сумма склада',
    cash: 'Касса',
    updateCash: 'Изменить остаток в кассе',
    exchangeRate: 'Курс Доллара (UZS)',
    aiInsights: 'ИИ-Советник',
    generateAI: 'Анализировать через ИИ',
    addModel: 'Добавить модель',
    manageModels: 'Управление линейкой товаров',
    pay: 'Оплатить',
    returned: 'Возвращено',
    completed: 'Завершено'
  }
};
